# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opfwd < Formula
  desc "1Password CLI Forwarding tool for seamless access from remote Linux machines"
  homepage "https://github.com/ezotrank/opfwd"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ezotrank/opfwd/releases/download/v0.1.8/opfwd_0.1.8_darwin_arm64.tar.gz"
      sha256 "3be857b77e7b7427f4d8a5b0a474c3edce3c27708800e8d1de8ef46db06507ae"

      def install
        bin.install "opfwd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ezotrank/opfwd/releases/download/v0.1.8/opfwd_0.1.8_linux_arm64.tar.gz"
        sha256 "111ab8c46c91fae33553939fa50faf24a6402cae4ab975ddd1fc6a273aa9fafb"

        def install
          bin.install "opfwd"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/opfwd --version")
  end
end
