# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opfwd < Formula
  desc "1Password CLI Forwarding tool for seamless access from remote Linux machines"
  homepage "https://github.com/ezotrank/opfwd"
  version "0.1.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ezotrank/opfwd/releases/download/v0.1.12/opfwd_0.1.12_darwin_arm64.tar.gz"
      sha256 "9812ad0af5e1d8a2ca0fcdf8e74a8155ccbe221915f44ddcb401b268a1ec1655"

      def install
        bin.install "opfwd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ezotrank/opfwd/releases/download/v0.1.12/opfwd_0.1.12_linux_arm64.tar.gz"
      sha256 "925880758948d1dcd07a0c36801cc613e2c8bcaaf001a296e6441c2e77e9f7d3"
      def install
        bin.install "opfwd"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/opfwd --version")
  end
end
