# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opfwd < Formula
  desc "1Password CLI Forwarding tool for seamless access from remote Linux machines"
  homepage "https://github.com/ezotrank/opfwd"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ezotrank/opfwd/releases/download/v0.1.9/opfwd_0.1.9_darwin_arm64.tar.gz"
      sha256 "a3d6e9e5fd4d6e34431ce7474e38a8927631faa1b2023aee014feeb76f44383f"

      def install
        bin.install "opfwd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ezotrank/opfwd/releases/download/v0.1.9/opfwd_0.1.9_linux_arm64.tar.gz"
        sha256 "be223bc4dbe56d493ff21bba7ace24381fc9cbdf277bdd72b9c8c3131705aa42"

        def install
          bin.install "opfwd"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/opfwd --version")
  end
end
